# base image built with jetson-containers:
# - on Orin NX 16GB with JetPack 6.0/Jetson Linux 36.3
# - needs 16GB swap to build: https://github.com/dusty-nv/jetson-containers/blob/master/docs/setup.md
# - then do: jetson-containers build --name event-orin cuda:12.2 pytorch:2.4 openai-triton:3.0.0
#
# to build this Dockerfile successfully:
# - make sure ssh agent has your github key, check with: ssh-add -l
# - then do: docker build -t event-orin-dfe -f Dockerfile.jetson --ssh default .
#
# to run it, do:
# - jetson-containers run -v .:/workspace event-orin-dfe

FROM event-orin:r36.3.0

ARG WS_SOURCE=.
ARG WS_TARGET=/workspace

# apt update
RUN apt update && apt upgrade -y --no-install-recommends \
    && apt install -y --no-install-recommends sudo vim python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

# set user to match current user
# https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user
ARG USERNAME=mavlab
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME
RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME
USER $USERNAME

# install python packages; ssh key to clone private repos
# https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
RUN mkdir -p ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts
RUN --mount=type=ssh,uid=1000 --mount=type=bind,source=$WS_SOURCE,target=$WS_TARGET \
    pip install -U -r $WS_TARGET/requirements-jetson.txt

WORKDIR $WS_TARGET
CMD ["/bin/bash"]
