visualizer:
  _target_: depth_from_events.callbacks.LiveVisualizer
  app_id: ${...name}
  server: 100.127.176.98:9876  # replace with your ip
  web: false
  compression: jpeg  # jpeg, png, false (to turn off)

defaults:
  - blueprint@visualizer.blueprint: full_cmax
