_target_: depth_from_events.dsec_old.DsecDataModule
root_dir: data/raw/dsec_old
time_window: 10000  # 10ms in us
count_thresh: 100000
train_seq_len: 100
train_crop: null  # hw for random, tlbr or null for fixed
val_crop: null
rectify: true
augmentations: [backward, polarity, horizontal]
return_events: true  # always
batch_size: 4
shuffle: true
num_workers: 8
download: false  # don't check downloads
