_target_: depth_from_events.flights.FlightDataModule
root_dir: data/raw/flights
time_window: 20000  # 20ms in s
train_seq_len: 100
train_recordings: null
train_crop: null  # hw for random, tlbr or null for fixed
val_recordings: null
val_crop: null
rectify: true
augmentations: [polarity, horizontal]
return_rotations: false  # override for pose
return_events: true  # always
batch_size: 8
shuffle: true
num_workers: 8
