defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

dataset:
  _target_: depth_from_events.flights.FlightSequence
  root_dir: data/raw/flights
  recording: rosbag2_2024-11-01-12-05-04_0
  time_window: 20000  # 20ms in us
  chunk_size: 100
  drop_last_chunk: true
  time: [16000000, 510000000]
  rectify: true

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: null
  shuffle: false
  num_workers: 8
  collate_fn:  # TODO: or hydra.utils.get_method?
    _target_: depth_from_events.data_utils.only_add_batch_dim
    _partial_: true

# network:
#   _target_: network.DepthPoseNetwork
#   _convert_: object
#   encoder_channels: 64
#   memory_channels: 64
#   decoder_channels: 64
#   activation_fn:
#     _target_: torch.nn.ELU
#     _partial_: true 
#   final_bias: false
#   padding_mode: reflect
#   scaling: [1, 0.01]  # disparity, pose

network:
  _target_: depth_from_events.network.WrappedDepthPoseNetwork  # TODO: unwrapped not faster?
  _convert_: object
  mode: depth
  encoder_channels: 64
  memory_channels: 64
  decoder_channels: 64
  activation_fn:
    _target_: torch.nn.ELU
    _partial_: true 
  final_bias: false
  padding_mode: reflect
  scaling: [1, 0.01]  # depth, pose

transform:
  _target_: depth_from_events.depth_disparity.DepthDisparityToFlow
  mode: depth
  min_depth: 0.1  # not used
  max_depth: 100  # not used

loss_function:
  _target_: depth_from_events.cmax.IterativeContrastMaximization
  use_events: true
  accumulation_window: 10
  base: 5
  keep_warping: true  # also check for going out outside base
  num_backprop_events: 0  # 0 = backprop all events
  select: null  # start:stop, null for everything

optimizer:
  _target_: torch.optim.Adam
  lr: 1.e-5

trainer:
  n_steps: 24000  # 24k steps at 50 Hz = 8 minutes
  clip_grad:
    _target_: torch.nn.utils.clip_grad_norm_  # TODO: does this work?
    _partial_: true
    max_norm: 1.0

checkpoint: logs/depth_from_events/a2a4gwea/checkpoints/epoch=49-step=35000.ckpt
state_dict_maps: {network.: "", disp_decoder: depth_decoder}
