defaults:
  - datamodule: office_flights
  - litmodule: train
  - network: disparity_pose_intrinsics
  - transform: disparity_to_flow
  - loss_functions@loss_functions.train:
    - cmax_iter
  - loss_functions@loss_functions.validate:
    - cmax_iter
    - rsat
  - optimizer: adam
  - scheduler: nothing
  - trainer: train
  - callbacks:
    - progress
    - checkpoint
  - logger: nothing
  - hydra: no_logging
  - _self_  # to disable warning

name: train
