defaults:
  - datamodule: uzh_fpv
  - litmodule: train
  - network: depth_pose
  - transform: depth_to_flow
  - loss_functions@loss_functions.train:
    - cmax_iter
    - scale_consistency
  - loss_functions@loss_functions.validate:
    - cmax_iter
    - rsat
    - depth_disparity
  - optimizer: adam
  - scheduler: nothing
  - trainer: train
  - callbacks:
    - progress
    - checkpoint
  - logger: nothing
  - hydra: no_logging
  - _self_  # to disable warning

wandb:
  entity: dfe-cvpr25
  project: depth_from_events

stage: train
name: ${stage}
runid: null  # start from checkpoint
checkpoint: null
